---
- name: Install Docker
  ansible.builtin.package:
    name: docker
    state: present

- name: Add Kubernetes apt repository
  ansible.builtin.apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes

- name: Install apt-transport-https
  ansible.builtin.package:
    name: apt-transport-https
    state: present

- name: Install kubelet, kubeadm, and kubectl
  ansible.builtin.package:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: Hold kubelet, kubeadm, and kubectl at current version
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
    hold: yes
  loop:
    - kubelet
    - kubeadm
    - kubectl
- name: Initialize the Kubernetes cluster
  command: kubeadm init --pod-network-cidr=10.244.0.0/16 # TODO Change this to network plugin
  when: inventory_hostname in groups['k8s_masters']
  register: kubeadm_init

- name: Create .kube directory
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    mode: '0755'
  when: kubeadm_init is changed

- name: Copy admin kubeconfig to user's home
  copy:
    src: "/etc/kubernetes/admin.conf"
    dest: "/home/{{ ansible_user }}/.kube/config"
    remote_src: yes
    owner: "{{ ansible_user }}"
    mode: '0644'
  when: kubeadm_init is changed

# Manual approach running separate task manually running to fetch join command from master node
# and execute it on the worker nodes
- name: Get join command
  command: kubeadm token create --print-join-command
  register: join_command
  when: inventory_hostname in groups['k8s_masters']
  changed_when: false
  check_mode: false

- name: Output join command
  debug:
    msg: "{{ join_command.stdout }}"
  when: join_command is defined
