---
- name: Setup Kubernetes Master Nodes
  hosts: k8s_masters
  become: true
  roles:
    - kubernetes_setup

- name: Setup Kubernetes Worker Nodes
  hosts: k8s_workers
  become: true
  roles:
    - kubernetes_setup
