---
- name: Update Cilium Configuration
  hosts: k8s_masters[0]  # Targeting the first master node for Helm operations
  become: yes
  vars:
    kube_config_path: "/home/ubuntu/.kube/config"  # TODO Ensure correct path, fix if needed I just assumed this would be it
    cilium_chart_name: "cilium/cilium"
    cilium_chart_version: "1.9.5"  # Specify target version for update
    cilium_namespace: "kube-system"
    hubble_relay_enabled: true
    hubble_ui_enabled: true
  
  tasks:
    - name: Ensure Helm is installed using binary installation
      ansible.builtin.get_url:
        url: "https://get.helm.sh/helm-v3.5.4-linux-amd64.tar.gz"
        dest: "/tmp/helm.tar.gz"
        mode: '0755'
      register: helm_download
      until: helm_download is succeeded

    - name: Update Cilium with new configurations using Helm
      community.kubernetes.helm:
        kubeconfig: "{{ kube_config_path }}"
        name: "cilium"
        chart_ref: "{{ cilium_chart_name }}"
        chart_version: "{{ cilium_chart_version }}"
        release_namespace: "{{ cilium_namespace }}"
        values:
          hubble:
            relay:
              enabled: "{{ hubble_relay_enabled }}"
            ui:
              enabled: "{{ hubble_ui_enabled }}"
        state: present
